name = "hari-tracker"
main = "src/worker.js"
compatibility_date = "2026-08-01"

# Created once with: npx wrangler kv namespace create HITS
# Then paste the returned namespace id below.
[[kv_namespaces]]
binding = "HITS"
id = "a7f19a198c504f2abff427da6e4e51ce"